### ISSUE TITLE
Crash when shutting down

### ISSUE THREAD

**Issue by cwensley** [ccc159/ViveTrack#2]
We're getting recent reports of this crash in Rhino on windows:

```
[ERROR] FATAL UNHANDLED EXCEPTION: System.DllNotFoundException: Unable to load DLL 'openvr_api': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Valve.VR.OpenVRInterop.ShutdownInternal()
   at Valve.VR.OpenVR.ShutdownInternal()
   at Valve.VR.OpenVR.Shutdown()
   at ViveTrack.OpenvrWrapper.Finalize()
[END ERROR]
```

**Comment by jingcheng-chen** [comment]
Thanks for your feedback. I will look into it once I have time.

**Comment by garciadelcastillo** [comment]
As per installation instructions:
```
Start Rhino, before running Grasshopper, type GrasshopperDeveloperSettings in Rhino console, and uncheck Memory load *.GHA assemblies using COFF byte arrays, then start Grasshopper.
```
